//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g 2012-04-17 15:52:25

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 168, 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;
using ConditionalAttribute = System.Diagnostics.ConditionalAttribute;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
public partial class MutexCLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int DIGIT=4;
	public const int FLOAT_DATATYPE=5;
	public const int HEX_DIGIT=6;
	public const int IDENTIFIER=7;
	public const int INTEGER_DATATYPE=8;
	public const int LETTER=9;
	public const int POINTER_DATATYPE=10;
	public const int SIGNED_UNSIGNED=11;
	public const int VOID_DATATYPE=12;

    // delegates
    // delegators

	public MutexCLexer()
	{
		OnCreated();
	}

	public MutexCLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public MutexCLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g"; } }

	private static readonly bool[] decisionCanBacktrack = new bool[0];

	public override IToken NextToken()
	{
		while (true)
		{
			if (input.LA(1) == CharStreamConstants.EndOfFile)
			{
				IToken eof = new CommonToken((ICharStream)input, CharStreamConstants.EndOfFile, TokenChannels.Default, input.Index, input.Index);
				eof.Line = Line;
				eof.CharPositionInLine = CharPositionInLine;
				return eof;
			}
			state.token = null;
			state.channel = TokenChannels.Default;
			state.tokenStartCharIndex = input.Index;
			state.tokenStartCharPositionInLine = input.CharPositionInLine;
			state.tokenStartLine = input.Line;
			state.text = null;
			try
			{
				int m = input.Mark();
				state.backtracking=1;
				state.failed=false;
				mTokens();
				state.backtracking=0;
				if (state.failed)
				{
					input.Rewind(m);
					input.Consume();
				}
				else
				{
					Emit();
					return state.token;
				}
			}
			catch (RecognitionException re)
			{
				// shouldn't happen in backtracking mode, but...
				ReportError(re);
				Recover(re);
			}
		}
	}

	public override void Memoize(IIntStream input, int ruleIndex, int ruleStartIndex)
	{
		if (state.backtracking > 1)
			base.Memoize(input, ruleIndex, ruleStartIndex);
	}

	public override bool AlreadyParsedRule(IIntStream input, int ruleIndex)
	{
		if (state.backtracking > 1)
			return base.AlreadyParsedRule(input, ruleIndex);

		return false;
	}

	[Conditional("ANTLR_TRACE")]
	protected virtual void OnCreated() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule(string ruleName, int ruleIndex) {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule(string ruleName, int ruleIndex) {}

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_POINTER_DATATYPE() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_POINTER_DATATYPE() {}

    // $ANTLR start "POINTER_DATATYPE"
    [GrammarRule("POINTER_DATATYPE")]
    private void mPOINTER_DATATYPE()
    {
    	EnterRule_POINTER_DATATYPE();
    	EnterRule("POINTER_DATATYPE", 1);
    	TraceIn("POINTER_DATATYPE", 1);
    		try
    		{
    		int _type = POINTER_DATATYPE;
    		int _channel = DefaultTokenChannel;
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:10:2: ( ( FLOAT_DATATYPE | INTEGER_DATATYPE | VOID_DATATYPE ) ( ' ' )* ( '*' )+ )
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:10:4: ( FLOAT_DATATYPE | INTEGER_DATATYPE | VOID_DATATYPE ) ( ' ' )* ( '*' )+
    		{
    		DebugLocation(10, 4);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:10:4: ( FLOAT_DATATYPE | INTEGER_DATATYPE | VOID_DATATYPE )
    		int alt1=3;
    		try { DebugEnterSubRule(1);
    		try { DebugEnterDecision(1, decisionCanBacktrack[1]);
    		switch (input.LA(1))
    		{
    		case 'd':
    		case 'f':
    			{
    			alt1 = 1;
    			}
    			break;
    		case 'c':
    		case 'i':
    		case 'l':
    		case 's':
    		case 'u':
    			{
    			alt1 = 2;
    			}
    			break;
    		case 'v':
    			{
    			alt1 = 3;
    			}
    			break;
    		default:
    			{
    				if (state.backtracking>0) {state.failed=true; return;}
    				NoViableAltException nvae = new NoViableAltException("", 1, 0, input);
    				DebugRecognitionException(nvae);
    				throw nvae;
    			}
    		}

    		} finally { DebugExitDecision(1); }
    		switch (alt1)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:10:5: FLOAT_DATATYPE
    			{
    			DebugLocation(10, 5);
    			mFLOAT_DATATYPE(); if (state.failed) return;

    			}
    			break;
    		case 2:
    			DebugEnterAlt(2);
    			// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:10:22: INTEGER_DATATYPE
    			{
    			DebugLocation(10, 22);
    			mINTEGER_DATATYPE(); if (state.failed) return;

    			}
    			break;
    		case 3:
    			DebugEnterAlt(3);
    			// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:10:41: VOID_DATATYPE
    			{
    			DebugLocation(10, 41);
    			mVOID_DATATYPE(); if (state.failed) return;

    			}
    			break;

    		}
    		} finally { DebugExitSubRule(1); }

    		DebugLocation(10, 56);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:10:56: ( ' ' )*
    		try { DebugEnterSubRule(2);
    		while (true)
    		{
    			int alt2=2;
    			try { DebugEnterDecision(2, decisionCanBacktrack[2]);
    			int LA2_0 = input.LA(1);

    			if ((LA2_0==' '))
    			{
    				alt2 = 1;
    			}


    			} finally { DebugExitDecision(2); }
    			switch ( alt2 )
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:10:56: ' '
    				{
    				DebugLocation(10, 56);
    				Match(' '); if (state.failed) return;

    				}
    				break;

    			default:
    				goto loop2;
    			}
    		}

    		loop2:
    			;

    		} finally { DebugExitSubRule(2); }

    		DebugLocation(10, 61);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:10:61: ( '*' )+
    		int cnt3=0;
    		try { DebugEnterSubRule(3);
    		while (true)
    		{
    			int alt3=2;
    			try { DebugEnterDecision(3, decisionCanBacktrack[3]);
    			int LA3_0 = input.LA(1);

    			if ((LA3_0=='*'))
    			{
    				alt3 = 1;
    			}


    			} finally { DebugExitDecision(3); }
    			switch (alt3)
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:10:61: '*'
    				{
    				DebugLocation(10, 61);
    				Match('*'); if (state.failed) return;

    				}
    				break;

    			default:
    				if (cnt3 >= 1)
    					goto loop3;

    				if (state.backtracking>0) {state.failed=true; return;}
    				EarlyExitException eee3 = new EarlyExitException( 3, input );
    				DebugRecognitionException(eee3);
    				throw eee3;
    			}
    			cnt3++;
    		}
    		loop3:
    			;

    		} finally { DebugExitSubRule(3); }


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("POINTER_DATATYPE", 1);
    		LeaveRule("POINTER_DATATYPE", 1);
    		LeaveRule_POINTER_DATATYPE();
        }
    }
    // $ANTLR end "POINTER_DATATYPE"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_VOID_DATATYPE() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_VOID_DATATYPE() {}

    // $ANTLR start "VOID_DATATYPE"
    [GrammarRule("VOID_DATATYPE")]
    private void mVOID_DATATYPE()
    {
    	EnterRule_VOID_DATATYPE();
    	EnterRule("VOID_DATATYPE", 2);
    	TraceIn("VOID_DATATYPE", 2);
    		try
    		{
    		int _type = VOID_DATATYPE;
    		int _channel = DefaultTokenChannel;
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:13:2: ( 'void' )
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:13:5: 'void'
    		{
    		DebugLocation(13, 5);
    		Match("void"); if (state.failed) return;


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("VOID_DATATYPE", 2);
    		LeaveRule("VOID_DATATYPE", 2);
    		LeaveRule_VOID_DATATYPE();
        }
    }
    // $ANTLR end "VOID_DATATYPE"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_FLOAT_DATATYPE() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_FLOAT_DATATYPE() {}

    // $ANTLR start "FLOAT_DATATYPE"
    [GrammarRule("FLOAT_DATATYPE")]
    private void mFLOAT_DATATYPE()
    {
    	EnterRule_FLOAT_DATATYPE();
    	EnterRule("FLOAT_DATATYPE", 3);
    	TraceIn("FLOAT_DATATYPE", 3);
    		try
    		{
    		int _type = FLOAT_DATATYPE;
    		int _channel = DefaultTokenChannel;
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:14:16: ( 'float' | 'double' )
    		int alt4=2;
    		try { DebugEnterDecision(4, decisionCanBacktrack[4]);
    		int LA4_0 = input.LA(1);

    		if ((LA4_0=='f'))
    		{
    			alt4 = 1;
    		}
    		else if ((LA4_0=='d'))
    		{
    			alt4 = 2;
    		}
    		else
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			NoViableAltException nvae = new NoViableAltException("", 4, 0, input);
    			DebugRecognitionException(nvae);
    			throw nvae;
    		}
    		} finally { DebugExitDecision(4); }
    		switch (alt4)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:14:18: 'float'
    			{
    			DebugLocation(14, 18);
    			Match("float"); if (state.failed) return;


    			}
    			break;
    		case 2:
    			DebugEnterAlt(2);
    			// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:14:28: 'double'
    			{
    			DebugLocation(14, 28);
    			Match("double"); if (state.failed) return;


    			}
    			break;

    		}
    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("FLOAT_DATATYPE", 3);
    		LeaveRule("FLOAT_DATATYPE", 3);
    		LeaveRule_FLOAT_DATATYPE();
        }
    }
    // $ANTLR end "FLOAT_DATATYPE"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_INTEGER_DATATYPE() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_INTEGER_DATATYPE() {}

    // $ANTLR start "INTEGER_DATATYPE"
    [GrammarRule("INTEGER_DATATYPE")]
    private void mINTEGER_DATATYPE()
    {
    	EnterRule_INTEGER_DATATYPE();
    	EnterRule("INTEGER_DATATYPE", 4);
    	TraceIn("INTEGER_DATATYPE", 4);
    		try
    		{
    		int _type = INTEGER_DATATYPE;
    		int _channel = DefaultTokenChannel;
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:16:18: ( ( SIGNED_UNSIGNED )? ( 'short' | 'int' | 'long' | 'char' ) )
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:16:20: ( SIGNED_UNSIGNED )? ( 'short' | 'int' | 'long' | 'char' )
    		{
    		DebugLocation(16, 20);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:16:20: ( SIGNED_UNSIGNED )?
    		int alt5=2;
    		try { DebugEnterSubRule(5);
    		try { DebugEnterDecision(5, decisionCanBacktrack[5]);
    		int LA5_0 = input.LA(1);

    		if ((LA5_0=='s'))
    		{
    			int LA5_1 = input.LA(2);

    			if ((LA5_1=='i'))
    			{
    				alt5 = 1;
    			}
    		}
    		else if ((LA5_0=='u'))
    		{
    			alt5 = 1;
    		}
    		} finally { DebugExitDecision(5); }
    		switch (alt5)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:16:21: SIGNED_UNSIGNED
    			{
    			DebugLocation(16, 21);
    			mSIGNED_UNSIGNED(); if (state.failed) return;

    			}
    			break;

    		}
    		} finally { DebugExitSubRule(5); }

    		DebugLocation(16, 39);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:16:39: ( 'short' | 'int' | 'long' | 'char' )
    		int alt6=4;
    		try { DebugEnterSubRule(6);
    		try { DebugEnterDecision(6, decisionCanBacktrack[6]);
    		switch (input.LA(1))
    		{
    		case 's':
    			{
    			alt6 = 1;
    			}
    			break;
    		case 'i':
    			{
    			alt6 = 2;
    			}
    			break;
    		case 'l':
    			{
    			alt6 = 3;
    			}
    			break;
    		case 'c':
    			{
    			alt6 = 4;
    			}
    			break;
    		default:
    			{
    				if (state.backtracking>0) {state.failed=true; return;}
    				NoViableAltException nvae = new NoViableAltException("", 6, 0, input);
    				DebugRecognitionException(nvae);
    				throw nvae;
    			}
    		}

    		} finally { DebugExitDecision(6); }
    		switch (alt6)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:16:40: 'short'
    			{
    			DebugLocation(16, 40);
    			Match("short"); if (state.failed) return;


    			}
    			break;
    		case 2:
    			DebugEnterAlt(2);
    			// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:16:50: 'int'
    			{
    			DebugLocation(16, 50);
    			Match("int"); if (state.failed) return;


    			}
    			break;
    		case 3:
    			DebugEnterAlt(3);
    			// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:16:58: 'long'
    			{
    			DebugLocation(16, 58);
    			Match("long"); if (state.failed) return;


    			}
    			break;
    		case 4:
    			DebugEnterAlt(4);
    			// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:16:67: 'char'
    			{
    			DebugLocation(16, 67);
    			Match("char"); if (state.failed) return;


    			}
    			break;

    		}
    		} finally { DebugExitSubRule(6); }


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("INTEGER_DATATYPE", 4);
    		LeaveRule("INTEGER_DATATYPE", 4);
    		LeaveRule_INTEGER_DATATYPE();
        }
    }
    // $ANTLR end "INTEGER_DATATYPE"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_SIGNED_UNSIGNED() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_SIGNED_UNSIGNED() {}

    // $ANTLR start "SIGNED_UNSIGNED"
    [GrammarRule("SIGNED_UNSIGNED")]
    private void mSIGNED_UNSIGNED()
    {
    	EnterRule_SIGNED_UNSIGNED();
    	EnterRule("SIGNED_UNSIGNED", 5);
    	TraceIn("SIGNED_UNSIGNED", 5);
    		try
    		{
    		int _type = SIGNED_UNSIGNED;
    		int _channel = DefaultTokenChannel;
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:18:17: ( 'signed' | 'unsigned' )
    		int alt7=2;
    		try { DebugEnterDecision(7, decisionCanBacktrack[7]);
    		int LA7_0 = input.LA(1);

    		if ((LA7_0=='s'))
    		{
    			alt7 = 1;
    		}
    		else if ((LA7_0=='u'))
    		{
    			alt7 = 2;
    		}
    		else
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			NoViableAltException nvae = new NoViableAltException("", 7, 0, input);
    			DebugRecognitionException(nvae);
    			throw nvae;
    		}
    		} finally { DebugExitDecision(7); }
    		switch (alt7)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:18:19: 'signed'
    			{
    			DebugLocation(18, 19);
    			Match("signed"); if (state.failed) return;


    			}
    			break;
    		case 2:
    			DebugEnterAlt(2);
    			// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:18:30: 'unsigned'
    			{
    			DebugLocation(18, 30);
    			Match("unsigned"); if (state.failed) return;


    			}
    			break;

    		}
    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("SIGNED_UNSIGNED", 5);
    		LeaveRule("SIGNED_UNSIGNED", 5);
    		LeaveRule_SIGNED_UNSIGNED();
        }
    }
    // $ANTLR end "SIGNED_UNSIGNED"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_IDENTIFIER() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_IDENTIFIER() {}

    // $ANTLR start "IDENTIFIER"
    [GrammarRule("IDENTIFIER")]
    private void mIDENTIFIER()
    {
    	EnterRule_IDENTIFIER();
    	EnterRule("IDENTIFIER", 6);
    	TraceIn("IDENTIFIER", 6);
    		try
    		{
    		int _type = IDENTIFIER;
    		int _channel = DefaultTokenChannel;
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:21:2: ( LETTER ( LETTER | DIGIT )* )
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:21:4: LETTER ( LETTER | DIGIT )*
    		{
    		DebugLocation(21, 4);
    		mLETTER(); if (state.failed) return;
    		DebugLocation(21, 11);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:21:11: ( LETTER | DIGIT )*
    		try { DebugEnterSubRule(8);
    		while (true)
    		{
    			int alt8=2;
    			try { DebugEnterDecision(8, decisionCanBacktrack[8]);
    			int LA8_0 = input.LA(1);

    			if (((LA8_0>='0' && LA8_0<='9')||(LA8_0>='A' && LA8_0<='Z')||LA8_0=='_'||(LA8_0>='a' && LA8_0<='z')))
    			{
    				alt8 = 1;
    			}


    			} finally { DebugExitDecision(8); }
    			switch ( alt8 )
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:
    				{
    				DebugLocation(21, 11);
    				input.Consume();
    				state.failed=false;

    				}
    				break;

    			default:
    				goto loop8;
    			}
    		}

    		loop8:
    			;

    		} finally { DebugExitSubRule(8); }


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("IDENTIFIER", 6);
    		LeaveRule("IDENTIFIER", 6);
    		LeaveRule_IDENTIFIER();
        }
    }
    // $ANTLR end "IDENTIFIER"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_LETTER() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_LETTER() {}

    // $ANTLR start "LETTER"
    [GrammarRule("LETTER")]
    private void mLETTER()
    {
    	EnterRule_LETTER();
    	EnterRule("LETTER", 7);
    	TraceIn("LETTER", 7);
    		try
    		{
    		int _type = LETTER;
    		int _channel = DefaultTokenChannel;
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:23:8: ( 'A' .. 'Z' | 'a' .. 'z' | '_' )
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:
    		{
    		DebugLocation(23, 8);
    		if ((input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z'))
    		{
    			input.Consume();
    		state.failed=false;
    		}
    		else
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("LETTER", 7);
    		LeaveRule("LETTER", 7);
    		LeaveRule_LETTER();
        }
    }
    // $ANTLR end "LETTER"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_HEX_DIGIT() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_HEX_DIGIT() {}

    // $ANTLR start "HEX_DIGIT"
    [GrammarRule("HEX_DIGIT")]
    private void mHEX_DIGIT()
    {
    	EnterRule_HEX_DIGIT();
    	EnterRule("HEX_DIGIT", 8);
    	TraceIn("HEX_DIGIT", 8);
    		try
    		{
    		int _type = HEX_DIGIT;
    		int _channel = DefaultTokenChannel;
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:25:11: ( DIGIT | 'a' .. 'f' | 'A' .. 'F' )
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:
    		{
    		DebugLocation(25, 11);
    		if ((input.LA(1)>='0' && input.LA(1)<='9')||(input.LA(1)>='A' && input.LA(1)<='F')||(input.LA(1)>='a' && input.LA(1)<='f'))
    		{
    			input.Consume();
    		state.failed=false;
    		}
    		else
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("HEX_DIGIT", 8);
    		LeaveRule("HEX_DIGIT", 8);
    		LeaveRule_HEX_DIGIT();
        }
    }
    // $ANTLR end "HEX_DIGIT"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_DIGIT() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_DIGIT() {}

    // $ANTLR start "DIGIT"
    [GrammarRule("DIGIT")]
    private void mDIGIT()
    {
    	EnterRule_DIGIT();
    	EnterRule("DIGIT", 9);
    	TraceIn("DIGIT", 9);
    		try
    		{
    		int _type = DIGIT;
    		int _channel = DefaultTokenChannel;
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:27:7: ( '0' .. '9' )
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:
    		{
    		DebugLocation(27, 7);
    		if ((input.LA(1)>='0' && input.LA(1)<='9'))
    		{
    			input.Consume();
    		state.failed=false;
    		}
    		else
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("DIGIT", 9);
    		LeaveRule("DIGIT", 9);
    		LeaveRule_DIGIT();
        }
    }
    // $ANTLR end "DIGIT"

    public override void mTokens()
    {
    	// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:39: ( POINTER_DATATYPE | VOID_DATATYPE | FLOAT_DATATYPE | INTEGER_DATATYPE | SIGNED_UNSIGNED | IDENTIFIER | LETTER | HEX_DIGIT | DIGIT )
    	int alt9=9;
    	try { DebugEnterDecision(9, decisionCanBacktrack[9]);
    	switch (input.LA(1))
    	{
    	case 'v':
    		{
    		int LA9_1 = input.LA(2);

    		if ((EvaluatePredicate(synpred1_MutexCLexer_fragment)))
    		{
    			alt9 = 1;
    		}
    		else if ((EvaluatePredicate(synpred2_MutexCLexer_fragment)))
    		{
    			alt9 = 2;
    		}
    		else if ((EvaluatePredicate(synpred6_MutexCLexer_fragment)))
    		{
    			alt9 = 6;
    		}
    		else if ((EvaluatePredicate(synpred7_MutexCLexer_fragment)))
    		{
    			alt9 = 7;
    		}
    		else
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			NoViableAltException nvae = new NoViableAltException("", 9, 1, input);
    			DebugRecognitionException(nvae);
    			throw nvae;
    		}
    		}
    		break;
    	case 'd':
    	case 'f':
    		{
    		int LA9_6 = input.LA(2);

    		if ((EvaluatePredicate(synpred1_MutexCLexer_fragment)))
    		{
    			alt9 = 1;
    		}
    		else if ((EvaluatePredicate(synpred3_MutexCLexer_fragment)))
    		{
    			alt9 = 3;
    		}
    		else if ((EvaluatePredicate(synpred6_MutexCLexer_fragment)))
    		{
    			alt9 = 6;
    		}
    		else if ((EvaluatePredicate(synpred7_MutexCLexer_fragment)))
    		{
    			alt9 = 7;
    		}
    		else if ((EvaluatePredicate(synpred8_MutexCLexer_fragment)))
    		{
    			alt9 = 8;
    		}
    		else
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			NoViableAltException nvae = new NoViableAltException("", 9, 6, input);
    			DebugRecognitionException(nvae);
    			throw nvae;
    		}
    		}
    		break;
    	case 's':
    	case 'u':
    		{
    		int LA9_9 = input.LA(2);

    		if ((EvaluatePredicate(synpred1_MutexCLexer_fragment)))
    		{
    			alt9 = 1;
    		}
    		else if ((EvaluatePredicate(synpred4_MutexCLexer_fragment)))
    		{
    			alt9 = 4;
    		}
    		else if ((EvaluatePredicate(synpred5_MutexCLexer_fragment)))
    		{
    			alt9 = 5;
    		}
    		else if ((EvaluatePredicate(synpred6_MutexCLexer_fragment)))
    		{
    			alt9 = 6;
    		}
    		else if ((EvaluatePredicate(synpred7_MutexCLexer_fragment)))
    		{
    			alt9 = 7;
    		}
    		else
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			NoViableAltException nvae = new NoViableAltException("", 9, 9, input);
    			DebugRecognitionException(nvae);
    			throw nvae;
    		}
    		}
    		break;
    	case 'c':
    		{
    		int LA9_12 = input.LA(2);

    		if ((EvaluatePredicate(synpred1_MutexCLexer_fragment)))
    		{
    			alt9 = 1;
    		}
    		else if ((EvaluatePredicate(synpred4_MutexCLexer_fragment)))
    		{
    			alt9 = 4;
    		}
    		else if ((EvaluatePredicate(synpred6_MutexCLexer_fragment)))
    		{
    			alt9 = 6;
    		}
    		else if ((EvaluatePredicate(synpred7_MutexCLexer_fragment)))
    		{
    			alt9 = 7;
    		}
    		else if ((EvaluatePredicate(synpred8_MutexCLexer_fragment)))
    		{
    			alt9 = 8;
    		}
    		else
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			NoViableAltException nvae = new NoViableAltException("", 9, 12, input);
    			DebugRecognitionException(nvae);
    			throw nvae;
    		}
    		}
    		break;
    	case 'A':
    	case 'B':
    	case 'C':
    	case 'D':
    	case 'E':
    	case 'F':
    	case 'a':
    	case 'b':
    	case 'e':
    		{
    		int LA9_13 = input.LA(2);

    		if ((EvaluatePredicate(synpred6_MutexCLexer_fragment)))
    		{
    			alt9 = 6;
    		}
    		else if ((EvaluatePredicate(synpred7_MutexCLexer_fragment)))
    		{
    			alt9 = 7;
    		}
    		else if ((EvaluatePredicate(synpred8_MutexCLexer_fragment)))
    		{
    			alt9 = 8;
    		}
    		else
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			NoViableAltException nvae = new NoViableAltException("", 9, 13, input);
    			DebugRecognitionException(nvae);
    			throw nvae;
    		}
    		}
    		break;
    	case 'i':
    	case 'l':
    		{
    		int LA9_14 = input.LA(2);

    		if ((EvaluatePredicate(synpred1_MutexCLexer_fragment)))
    		{
    			alt9 = 1;
    		}
    		else if ((EvaluatePredicate(synpred4_MutexCLexer_fragment)))
    		{
    			alt9 = 4;
    		}
    		else if ((EvaluatePredicate(synpred6_MutexCLexer_fragment)))
    		{
    			alt9 = 6;
    		}
    		else if ((EvaluatePredicate(synpred7_MutexCLexer_fragment)))
    		{
    			alt9 = 7;
    		}
    		else
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			NoViableAltException nvae = new NoViableAltException("", 9, 14, input);
    			DebugRecognitionException(nvae);
    			throw nvae;
    		}
    		}
    		break;
    	case 'G':
    	case 'H':
    	case 'I':
    	case 'J':
    	case 'K':
    	case 'L':
    	case 'M':
    	case 'N':
    	case 'O':
    	case 'P':
    	case 'Q':
    	case 'R':
    	case 'S':
    	case 'T':
    	case 'U':
    	case 'V':
    	case 'W':
    	case 'X':
    	case 'Y':
    	case 'Z':
    	case '_':
    	case 'g':
    	case 'h':
    	case 'j':
    	case 'k':
    	case 'm':
    	case 'n':
    	case 'o':
    	case 'p':
    	case 'q':
    	case 'r':
    	case 't':
    	case 'w':
    	case 'x':
    	case 'y':
    	case 'z':
    		{
    		int LA9_15 = input.LA(2);

    		if ((EvaluatePredicate(synpred6_MutexCLexer_fragment)))
    		{
    			alt9 = 6;
    		}
    		else if ((EvaluatePredicate(synpred7_MutexCLexer_fragment)))
    		{
    			alt9 = 7;
    		}
    		else
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			NoViableAltException nvae = new NoViableAltException("", 9, 15, input);
    			DebugRecognitionException(nvae);
    			throw nvae;
    		}
    		}
    		break;
    	case '0':
    	case '1':
    	case '2':
    	case '3':
    	case '4':
    	case '5':
    	case '6':
    	case '7':
    	case '8':
    	case '9':
    		{
    		int LA9_16 = input.LA(2);

    		if ((EvaluatePredicate(synpred8_MutexCLexer_fragment)))
    		{
    			alt9 = 8;
    		}
    		else if ((true))
    		{
    			alt9 = 9;
    		}
    		else
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			NoViableAltException nvae = new NoViableAltException("", 9, 16, input);
    			DebugRecognitionException(nvae);
    			throw nvae;
    		}
    		}
    		break;
    	default:
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			NoViableAltException nvae = new NoViableAltException("", 9, 0, input);
    			DebugRecognitionException(nvae);
    			throw nvae;
    		}
    	}

    	} finally { DebugExitDecision(9); }
    	switch (alt9)
    	{
    	case 1:
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:41: POINTER_DATATYPE
    		{
    		DebugLocation(1, 41);
    		mPOINTER_DATATYPE(); if (state.failed) return;

    		}
    		break;
    	case 2:
    		DebugEnterAlt(2);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:58: VOID_DATATYPE
    		{
    		DebugLocation(1, 58);
    		mVOID_DATATYPE(); if (state.failed) return;

    		}
    		break;
    	case 3:
    		DebugEnterAlt(3);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:72: FLOAT_DATATYPE
    		{
    		DebugLocation(1, 72);
    		mFLOAT_DATATYPE(); if (state.failed) return;

    		}
    		break;
    	case 4:
    		DebugEnterAlt(4);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:87: INTEGER_DATATYPE
    		{
    		DebugLocation(1, 87);
    		mINTEGER_DATATYPE(); if (state.failed) return;

    		}
    		break;
    	case 5:
    		DebugEnterAlt(5);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:104: SIGNED_UNSIGNED
    		{
    		DebugLocation(1, 104);
    		mSIGNED_UNSIGNED(); if (state.failed) return;

    		}
    		break;
    	case 6:
    		DebugEnterAlt(6);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:120: IDENTIFIER
    		{
    		DebugLocation(1, 120);
    		mIDENTIFIER(); if (state.failed) return;

    		}
    		break;
    	case 7:
    		DebugEnterAlt(7);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:131: LETTER
    		{
    		DebugLocation(1, 131);
    		mLETTER(); if (state.failed) return;

    		}
    		break;
    	case 8:
    		DebugEnterAlt(8);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:138: HEX_DIGIT
    		{
    		DebugLocation(1, 138);
    		mHEX_DIGIT(); if (state.failed) return;

    		}
    		break;
    	case 9:
    		DebugEnterAlt(9);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:148: DIGIT
    		{
    		DebugLocation(1, 148);
    		mDIGIT(); if (state.failed) return;

    		}
    		break;

    	}

    }
    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_synpred1_MutexCLexer_fragment() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_synpred1_MutexCLexer_fragment() {}

    // $ANTLR start synpred1_MutexCLexer
    public void synpred1_MutexCLexer_fragment()
    {
    	EnterRule_synpred1_MutexCLexer_fragment();
    	EnterRule("synpred1_MutexCLexer_fragment", 11);
    	TraceIn("synpred1_MutexCLexer_fragment", 11);
    	try
    	{
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:41: ( POINTER_DATATYPE )
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:41: POINTER_DATATYPE
    		{
    		DebugLocation(1, 41);
    		mPOINTER_DATATYPE(); if (state.failed) return;

    		}

    	}
    	finally
    	{
    		TraceOut("synpred1_MutexCLexer_fragment", 11);
    		LeaveRule("synpred1_MutexCLexer_fragment", 11);
    		LeaveRule_synpred1_MutexCLexer_fragment();
    	}
    }
    // $ANTLR end synpred1_MutexCLexer
    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_synpred2_MutexCLexer_fragment() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_synpred2_MutexCLexer_fragment() {}

    // $ANTLR start synpred2_MutexCLexer
    public void synpred2_MutexCLexer_fragment()
    {
    	EnterRule_synpred2_MutexCLexer_fragment();
    	EnterRule("synpred2_MutexCLexer_fragment", 12);
    	TraceIn("synpred2_MutexCLexer_fragment", 12);
    	try
    	{
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:58: ( VOID_DATATYPE )
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:58: VOID_DATATYPE
    		{
    		DebugLocation(1, 58);
    		mVOID_DATATYPE(); if (state.failed) return;

    		}

    	}
    	finally
    	{
    		TraceOut("synpred2_MutexCLexer_fragment", 12);
    		LeaveRule("synpred2_MutexCLexer_fragment", 12);
    		LeaveRule_synpred2_MutexCLexer_fragment();
    	}
    }
    // $ANTLR end synpred2_MutexCLexer
    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_synpred3_MutexCLexer_fragment() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_synpred3_MutexCLexer_fragment() {}

    // $ANTLR start synpred3_MutexCLexer
    public void synpred3_MutexCLexer_fragment()
    {
    	EnterRule_synpred3_MutexCLexer_fragment();
    	EnterRule("synpred3_MutexCLexer_fragment", 13);
    	TraceIn("synpred3_MutexCLexer_fragment", 13);
    	try
    	{
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:72: ( FLOAT_DATATYPE )
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:72: FLOAT_DATATYPE
    		{
    		DebugLocation(1, 72);
    		mFLOAT_DATATYPE(); if (state.failed) return;

    		}

    	}
    	finally
    	{
    		TraceOut("synpred3_MutexCLexer_fragment", 13);
    		LeaveRule("synpred3_MutexCLexer_fragment", 13);
    		LeaveRule_synpred3_MutexCLexer_fragment();
    	}
    }
    // $ANTLR end synpred3_MutexCLexer
    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_synpred4_MutexCLexer_fragment() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_synpred4_MutexCLexer_fragment() {}

    // $ANTLR start synpred4_MutexCLexer
    public void synpred4_MutexCLexer_fragment()
    {
    	EnterRule_synpred4_MutexCLexer_fragment();
    	EnterRule("synpred4_MutexCLexer_fragment", 14);
    	TraceIn("synpred4_MutexCLexer_fragment", 14);
    	try
    	{
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:87: ( INTEGER_DATATYPE )
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:87: INTEGER_DATATYPE
    		{
    		DebugLocation(1, 87);
    		mINTEGER_DATATYPE(); if (state.failed) return;

    		}

    	}
    	finally
    	{
    		TraceOut("synpred4_MutexCLexer_fragment", 14);
    		LeaveRule("synpred4_MutexCLexer_fragment", 14);
    		LeaveRule_synpred4_MutexCLexer_fragment();
    	}
    }
    // $ANTLR end synpred4_MutexCLexer
    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_synpred5_MutexCLexer_fragment() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_synpred5_MutexCLexer_fragment() {}

    // $ANTLR start synpred5_MutexCLexer
    public void synpred5_MutexCLexer_fragment()
    {
    	EnterRule_synpred5_MutexCLexer_fragment();
    	EnterRule("synpred5_MutexCLexer_fragment", 15);
    	TraceIn("synpred5_MutexCLexer_fragment", 15);
    	try
    	{
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:104: ( SIGNED_UNSIGNED )
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:104: SIGNED_UNSIGNED
    		{
    		DebugLocation(1, 104);
    		mSIGNED_UNSIGNED(); if (state.failed) return;

    		}

    	}
    	finally
    	{
    		TraceOut("synpred5_MutexCLexer_fragment", 15);
    		LeaveRule("synpred5_MutexCLexer_fragment", 15);
    		LeaveRule_synpred5_MutexCLexer_fragment();
    	}
    }
    // $ANTLR end synpred5_MutexCLexer
    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_synpred6_MutexCLexer_fragment() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_synpred6_MutexCLexer_fragment() {}

    // $ANTLR start synpred6_MutexCLexer
    public void synpred6_MutexCLexer_fragment()
    {
    	EnterRule_synpred6_MutexCLexer_fragment();
    	EnterRule("synpred6_MutexCLexer_fragment", 16);
    	TraceIn("synpred6_MutexCLexer_fragment", 16);
    	try
    	{
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:120: ( IDENTIFIER )
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:120: IDENTIFIER
    		{
    		DebugLocation(1, 120);
    		mIDENTIFIER(); if (state.failed) return;

    		}

    	}
    	finally
    	{
    		TraceOut("synpred6_MutexCLexer_fragment", 16);
    		LeaveRule("synpred6_MutexCLexer_fragment", 16);
    		LeaveRule_synpred6_MutexCLexer_fragment();
    	}
    }
    // $ANTLR end synpred6_MutexCLexer
    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_synpred7_MutexCLexer_fragment() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_synpred7_MutexCLexer_fragment() {}

    // $ANTLR start synpred7_MutexCLexer
    public void synpred7_MutexCLexer_fragment()
    {
    	EnterRule_synpred7_MutexCLexer_fragment();
    	EnterRule("synpred7_MutexCLexer_fragment", 17);
    	TraceIn("synpred7_MutexCLexer_fragment", 17);
    	try
    	{
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:131: ( LETTER )
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:
    		{
    		DebugLocation(1, 131);
    		if ((input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z'))
    		{
    			input.Consume();
    		state.failed=false;
    		}
    		else
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("synpred7_MutexCLexer_fragment", 17);
    		LeaveRule("synpred7_MutexCLexer_fragment", 17);
    		LeaveRule_synpred7_MutexCLexer_fragment();
    	}
    }
    // $ANTLR end synpred7_MutexCLexer
    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_synpred8_MutexCLexer_fragment() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_synpred8_MutexCLexer_fragment() {}

    // $ANTLR start synpred8_MutexCLexer
    public void synpred8_MutexCLexer_fragment()
    {
    	EnterRule_synpred8_MutexCLexer_fragment();
    	EnterRule("synpred8_MutexCLexer_fragment", 18);
    	TraceIn("synpred8_MutexCLexer_fragment", 18);
    	try
    	{
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:1:138: ( HEX_DIGIT )
    		DebugEnterAlt(1);
    		// D:\\wissen\\csharp\\GreedyStringTiling\\CTokenizer\\MutexCLexer.g:
    		{
    		DebugLocation(1, 138);
    		if ((input.LA(1)>='0' && input.LA(1)<='9')||(input.LA(1)>='A' && input.LA(1)<='F')||(input.LA(1)>='a' && input.LA(1)<='f'))
    		{
    			input.Consume();
    		state.failed=false;
    		}
    		else
    		{
    			if (state.backtracking>0) {state.failed=true; return;}
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("synpred8_MutexCLexer_fragment", 18);
    		LeaveRule("synpred8_MutexCLexer_fragment", 18);
    		LeaveRule_synpred8_MutexCLexer_fragment();
    	}
    }
    // $ANTLR end synpred8_MutexCLexer

	#region Synpreds
	private bool EvaluatePredicate(System.Action fragment)
	{
		bool success = false;
		state.backtracking++;
		try { DebugBeginBacktrack(state.backtracking);
		int start = input.Mark();
		try
		{
			fragment();
		}
		catch ( RecognitionException re )
		{
			System.Console.Error.WriteLine("impossible: "+re);
		}
		success = !state.failed;
		input.Rewind(start);
		} finally { DebugEndBacktrack(state.backtracking, success); }
		state.backtracking--;
		state.failed=false;
		return success;
	}
	#endregion Synpreds


	#region DFA

	protected override void InitDFAs()
	{
		base.InitDFAs();
	}

 
	#endregion

}
